[package]
name = "cryptography"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5", features = ["derive","cargo"] }
#aes-gcm = { version = "0.10", features = ["rand"] }
aes-gcm = "0.10"
rand = "0.8" 
hex = "0.4"
generic-array = "0.14"
typenum = "1.15"
